# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='userid',
        ),
        migrations.AddField(
            model_name='expertise',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('HighSchool', 'HighSchool'), ('College', 'College')], default='Primary', max_length=12),
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='expert',
            field=models.CharField(choices=[('English', 'English'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer', 'Computer'), ('SocialScience', 'SocialScience')], max_length=12),
        ),
    ]
