# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20170413_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HighestQualification', models.CharField(choices=[('HighSchool', 'HighSchool'), ('Intermediate', 'Intermediate'), ('BacheleorDegree', 'BacheleorDegree'), ('MasterDegree', 'MasterDegree'), ('Doctorate', 'Doctorate')], default='HighSchool', max_length=20)),
                ('university', models.CharField(blank=True, max_length=50)),
                ('Experience', models.IntegerField(blank=True, default=0, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='expertise',
            name='expert',
            field=models.CharField(choices=[('English', 'English'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Computer', 'Computer'), ('SocialScience', 'SocialScience')], default='English', max_length=12),
        ),
    ]
