# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20170414_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualifications',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='qualifications',
            old_name='HighestQualification',
            new_name='highestQualification',
        ),
    ]
