# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20170414_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qualifications',
            name='stream',
            field=models.CharField(choices=[('HighSchool', 'HighSchool'), ('Intermediate', 'Intermediate'), ('BacheleorDegree', 'BacheleorDegree'), ('MasterDegree', 'MasterDegree'), ('Doctorate', 'Doctorate')], default='ComputerScience', max_length=20),
        ),
    ]
