# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 06:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20170414_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', code='Invalid Name', message='please Enter A valid Name must have only alphabets')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='usertype',
            field=models.CharField(choices=[('Student', 'Student'), ('Tutor', 'Tutor')], default='Student', max_length=8),
        ),
    ]
