# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_auto_20170417_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifications',
            name='stream',
            field=models.CharField(choices=[('ComputerScience', 'ComputerScience'), ('informationTechnology', 'informationTechnology'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Meidcal', 'Meidcal'), ('Arts', 'Arts'), ('Accounts', 'Accounts'), ('Economics', 'Economics')], default='ComputerScience', max_length=20),
        ),
    ]
