# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20170418_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='subject',
            field=models.ForeignKey(default='select', on_delete=django.db.models.deletion.CASCADE, to='tutor.Subject'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='expert',
            field=models.ForeignKey(default='select', on_delete=django.db.models.deletion.CASCADE, to='tutor.Subject'),
        ),
    ]
