# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 05:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_auto_20170418_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.CharField(choices=[('I only teach from home', 'I only teach from home'), ('1 miles', '1 miles'), ('2 miles', '2 miles'), ('3 miles', '3 miles'), ('4 miles', '4 miles'), ('5 miles', '5 miles'), ('8 miles', '8 miles'), ('10 miles', '10 miles'), ('12 miles', '12 miles')], default='Select', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
