# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('streamid', models.AutoField(primary_key=True, serialize=False)),
                ('stream', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Stream'),
        ),
    ]
